### ISSUE TITLE
Bug with linebreaks in dependencies

### ISSUE THREAD

**Issue by jeroen** [r-hub/rdesc-parser#2]
Parsing the [DESCRIPTION for Rcpp](https://github.com/cran/Rcpp/blob/master/DESCRIPTION#L19-L20) we get:

```
[1] "RUnit"                 "inline"                "rbenchmark"            "knitr"                 "rmarkdown"            
[6] "pinp"                  "pkgKitten\n(>= 0.1.2)"
```

Note that `pkgKitten` includes a `\n` before the version. This messes up the formatting when we insert this back into a DESCRIPTION file. 

Another case is `dbplyr` which includes `rlang (>=\n0.2.0)` as a dependency.

**Comment by gaborcsardi** [comment]
We should probably just remove newlines from the dependency fields and replace them with spaces.

**Comment by jeroen** [comment]
I think we should be removing newlines everywhere? Such that a newline is only a delimiter.

**Comment by gaborcsardi** [comment]
No, in the paragraphs it makes sense to keep them. desc goes a long way to keep them everywhere, but we don't need to repeat that here.... I think it is ok to just remove them in the dependency fields and `Remotes`.

**Comment by jeroen** [comment]
In most cases the linebreaks are arbitrary artifacts of the dsc format. What is the case for retaining them in the json representation?

Maybe we can whitelist for which fields the linebreaks should be retained (e.g. `Title` and `Description`) and trim them by default for other fields?

**Comment by gaborcsardi** [comment]
We could. I guess these parsed fields are for the server side only. Desc tries hard to keep whitespace as is, because people are very opiniated about it. But also, why make an effort to remove it? I think we can just remove it from the specially parsed fields?

**Comment by gaborcsardi** [comment]
Do you put the whole description into the db? In that case we could remove it.

Btw some people use whitespace to create paragraphs.

**Comment by jeroen** [comment]
Yes I stick everything into the db. 

In my opinion, the whitespace is part of the `dsc` format, not the value. The whitespace loses meaning once you have parsed it in to json.

But in practice it only creates a problem for me for the fields that are included in PACKAGES:

```
 [1] "Package"               "Version"               "Priority"              "Depends"              
 [5] "Imports"               "LinkingTo"             "Suggests"              "Enhances"             
 [9] "License"               "License_is_FOSS"       "License_restricts_use" "OS_type"              
[13] "Archs"                 "MD5sum"                "NeedsCompilation"      "File"                 
[17] "Repository"
```

**Comment by gaborcsardi** [comment]
Here is an example that has multiple paragraphs: https://cran.rstudio.com/web/packages/RApiSerialize/DESCRIPTION

Anyway, I think if we want to reuse this package, then the whitespace removal should be optional. Is that ok?

Btw. can you pls include the `Built` field? It helps you check if a build time dependency has been updated.

**Comment by jeroen** [comment]
Optional makes sense, but what should be the default? I think they really should always be trimmed for dependency fields because there they actually mess up the output and have no meaning.

Is there any field other than `Description` that has meaningful paragraphs?

**Comment by gaborcsardi** [comment]
We can remove by default. We can also always remove from dependency fields including `Remotes`, and also `Built`, i.e. the fields that we parse.

**Comment by jeroen** [comment]
> Can you pls include the Built field? It helps you check if a build time dependency has been updated.

You mean include it in the PACKAGES file? Because the [CRAN PACKAGES](https://cran.r-project.org/bin/windows/contrib/3.6/PACKAGES) doesn't have this either. It will be available in the API of course, like all fields. I could also include it in the `PACKAGES` but I'm not sure that `available.packages()` will actually read it.

**Comment by gaborcsardi** [comment]
Yes, include it in the PACKAGES file. On CRAN it is included for macos, but
not for Windows.

If you have it there, then it is easy to check if a binary package has a
new build (with same versions number) in the repository.
